# Generated by Django 5.2.5 on 2025-08-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_cake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='img',
            field=models.ImageField(upload_to='cake/'),
        ),
    ]
