# Generated by Django 5.2.5 on 2025-08-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0003_alter_cake_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='knife',
            field=models.ImageField(blank=True, null=True, upload_to='knife/'),
        ),
    ]
