# Generated by Django 5.2.4 on 2025-09-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0004_cake_knife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(upload_to='static/birthday/'),
        ),
    ]
