# Generated by Django 5.2.4 on 2025-09-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0005_alter_img_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(upload_to='birthday/'),
        ),
    ]
